# Generated by Django 6.0 on 2026-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBapp', '0002_sitelogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLogo',
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('PG', 'PG')], default='1BHK', max_length=10),
            preserve_default=False,
        ),
    ]
