# Generated by Django 6.0 on 2026-01-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBapp', '0003_delete_sitelogo_property_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='property_type',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
